apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "chart.fullname" . }}-db
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: gp2

---

apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-{{ include "chart.fullname" . }}-rw
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "chart.fullname" . }}-db
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
