apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "chart.fullname" . }}-db
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  instances: 3
  storage:
    size: 1Gi
