
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-schema
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  schema.sql: |-
{{ .Files.Get "schema.sql" | indent 4}}

---

apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: {{ .Release.Name }}-atlas-schema
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schema:
    configMapKeyRef:
      key: schema.sql
      name: {{ .Release.Name }}-schema
  credentials:
    scheme: postgres
    host: pooler-broodx-frontend-rw
    userFrom:
      secretKeyRef:
        name: broodx-frontend-postgres-app
        key: user
    passwordFrom:
      secretKeyRef:
        name: broodx-frontend-postgres-app
        key: password
    database: app
    port: 5432
#    parameters:
#      sslmode: disable
