
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrations
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "migrations/*").AsConfig | indent 2 }}

---


apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  name: {{ .Release.Name }}-atlas-migration
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dir:
    configMapRef:
      name: {{ .Release.Name }}-migrations
  credentials:
    scheme: postgres
    host: pooler-broodx-frontend-rw.broodx.svc.cluster.local
    userFrom:
      secretKeyRef:
        name: broodx-frontend-postgres-app
        key: user
    passwordFrom:
      secretKeyRef:
        name: broodx-frontend-postgres-app
        key: password
    database: app
    port: 5432
#    parameters:
#      sslmode: disable
