
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-schema
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  schema.sql: |-
{{ .Files.Get "schema.sql" | indent 4}}

---

apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: {{ .Release.Name }}-atlas-schema
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schema:
    configMapKeyRef:
      key: schema.sql
      name: {{ .Release.Name }}-schema
