image:
  tag: bc22dc4e0c8fcff9b34e5ce33d087745e2af0170
service:
  port: 3001
ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging-2"
  enabled: true
  className: "nginx"
  hosts:
    - host: "www-staging.broodx.com"
      paths:
        - pathType: "Prefix"
          path: "/"
  tls:
    - hosts:
        - "www-staging.broodx.com"
      secretName: "broodx-frontend-tls"
