image:
  tag: d6b3528511ebf82c22c12f3f0695eaa0a0ae5ad1
service:
  port: 3001
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "www-staging.broodx.com"
      paths:
        - pathType: "Prefix"
          path: "/"
