image:
  tag: aa2116806fa6a23d5b163f877f3d8d19e35796ea
service:
  port: 3001
ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging-2"
  enabled: true
  className: "nginx"
  hosts:
    - host: "www-staging.broodx.com"
      paths:
        - pathType: "Prefix"
          path: "/"
  tls:
    - hosts:
        - "www-staging.broodx.com"
      secretName: "broodx-frontend-tls"
