name: Docker image build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.3"

      - uses: azure/setup-helm@v4.2.0
        with:
          version: "3.15.3"

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::356853385214:role/github-actions-broodx-frontend
          role-session-name: samplerolesession
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: broodx
          IMAGE_TAG: ${{ github.sha }}
          REGION: us-west-2
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update values.yaml
        run: |
          yq -i -e ".image.tag = \"$IMAGE_TAG\"" charts/broodx-frontend/values-staging.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add charts/broodx-frontend/values-staging.yaml
          git commit -m "Update staging image"
          git push
        env:
          IMAGE_TAG: ${{ github.sha }}
